FROM sqoop-base

ENV SPARK_VERSION=spark-3.1.1-bin-hadoop3.2
ENV SPARK_URL https://www.apache.org/dist/spark/spark-3.1.1/${SPARK_VERSION}.tgz

RUN set -x \
    && curl -fSL "$SPARK_URL" -o /tmp/spark.tar.gz \
    && tar -xvzf /tmp/spark.tar.gz -C /opt/ \
    && rm /tmp/spark.tar.gz*

ENV SPARK_HOME=/opt/$SPARK_VERSION
ENV PATH $SPARK_HOME/bin:$PATH

COPY conf/hive-site.xml $SPARK_HOME/conf/
COPY conf/core-site.xml $SPARK_HOME/conf/
COPY conf/yarn-site.xml $SPARK_HOME/conf/

ENV HADOOP_CONF_DIR=$SPARK_HOME/conf

COPY entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/entrypoint.sh

ENV PYSPARK_PYTHON=python3
ENV PYTHONHASHSEED 1

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]