FROM ubuntu:20.04

LABEL maintainer="p.patcoding@gmail.com"

# install necessary tools
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
	build-essential \
    curl \
    git \
    less \
    nano \
    netcat \
    net-tools \
    software-properties-common \
    wget \
    vim

# install JAVA
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    openjdk-8-jdk
ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-arm64/

# install python
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    python3.8 python3-pip
RUN python3 -m pip install pip --upgrade
RUN python3 -m pip install wheel